// <auto-generated />
using System;
using Library_Management_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Management_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129081250_0.8")]
    partial class _08
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_Management_API.Models.Book", b =>
                {
                    b.Property<int>("book_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("book_id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("available_copies")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("publication_year")
                        .HasColumnType("int");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_copies")
                        .HasColumnType("int");

                    b.HasKey("book_id");

                    b.ToTable("BookTable");
                });

            modelBuilder.Entity("Library_Management_API.Models.Borrow_Record", b =>
                {
                    b.Property<int>("borrow_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("borrow_id"));

                    b.Property<DateOnly?>("approval_date")
                        .HasColumnType("date");

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("due_date")
                        .HasColumnType("date");

                    b.Property<bool>("isWalkIn")
                        .HasColumnType("bit");

                    b.Property<int>("member_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("pickup_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("request_date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("return_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("borrow_id");

                    b.HasIndex("book_id");

                    b.HasIndex("member_id");

                    b.ToTable("Borrow_RecordTable");
                });

            modelBuilder.Entity("Library_Management_API.Models.Fine", b =>
                {
                    b.Property<int>("fine_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fine_id"));

                    b.Property<int>("borrow_id")
                        .HasColumnType("int");

                    b.Property<decimal>("fine_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("is_paid")
                        .HasColumnType("bit");

                    b.Property<int>("overdue_days")
                        .HasColumnType("int");

                    b.HasKey("fine_id");

                    b.HasIndex("borrow_id");

                    b.ToTable("FineTable");
                });

            modelBuilder.Entity("Library_Management_API.Models.Member", b =>
                {
                    b.Property<int>("member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("member_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("member_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("membership_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("member_id");

                    b.ToTable("MemberTable");
                });

            modelBuilder.Entity("Library_Management_API.Models.Borrow_Record", b =>
                {
                    b.HasOne("Library_Management_API.Models.Book", "Book")
                        .WithMany("Borrow_Records")
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Management_API.Models.Member", "Member")
                        .WithMany("Borrow_Records")
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Library_Management_API.Models.Fine", b =>
                {
                    b.HasOne("Library_Management_API.Models.Borrow_Record", "Borrow_Record")
                        .WithMany()
                        .HasForeignKey("borrow_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrow_Record");
                });

            modelBuilder.Entity("Library_Management_API.Models.Book", b =>
                {
                    b.Navigation("Borrow_Records");
                });

            modelBuilder.Entity("Library_Management_API.Models.Member", b =>
                {
                    b.Navigation("Borrow_Records");
                });
#pragma warning restore 612, 618
        }
    }
}
